In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [3]:
a1.shape

(4,)

In [4]:
a1.ndim

1

In [5]:
a2=np.array([[1,2,3,4],[5,6,7,8]])
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
a2.shape,a2.ndim

((2, 4), 2)

In [10]:
a3=np.array([[[1,2,3,4],[5,6,7,8],[10,11,12,13]],
             [[2,3,4,5],[3,4,5,6],[5,6,7,8]]])

In [11]:
a3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [10, 11, 12, 13]],

       [[ 2,  3,  4,  5],
        [ 3,  4,  5,  6],
        [ 5,  6,  7,  8]]])

In [14]:
a3.shape,a3.ndim

((2, 3, 4), 3)

In [16]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [17]:
a1.size,a2.size,a3.size

(4, 8, 24)

In [18]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [19]:
import pandas as pd


In [20]:
ones=np.ones((10,2))

In [21]:
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [22]:
ones.shape

(10, 2)

In [23]:
zeros=np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [24]:
zeros.shape

(7, 2, 3)

In [25]:
random_array_1=np.arange(0,100,3)
random_array_1

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [26]:
random_array_2=np.random.randint(1,10,size=(7,2))
random_array_2

array([[6, 4],
       [5, 8],
       [8, 8],
       [7, 5],
       [5, 1],
       [2, 2],
       [7, 6]])

In [28]:
random_array_2.shape

(7, 2)

In [31]:
random_array_3=np.random.random(size=(3,5))
random_array_3

array([[0.80415591, 0.1713152 , 0.62405946, 0.38903821, 0.91891017],
       [0.72351235, 0.7762253 , 0.94828461, 0.44648257, 0.68238246],
       [0.77993709, 0.23186095, 0.06407192, 0.44962418, 0.59694814]])

In [35]:
np.random.seed(42)
random_array_4=np.random.randint(0,10,size=(4,6))
random_array_4

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [36]:
var=np.random.randint(1,10,size=(3,7))
var

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [37]:
np.unique(var)

array([1, 2, 3, 4, 5, 7, 9])

In [38]:
var[0]

array([9, 1, 3, 7, 4, 9, 3])

In [39]:
var[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [40]:
var[:2,:2]

array([[9, 1],
       [5, 3]])

In [52]:
var1=np.random.randint(1,10,size=(3,5))
var1

array([[4, 8, 7, 9, 8],
       [5, 2, 5, 8, 9],
       [9, 1, 9, 7, 9]])

In [53]:
var2=np.ones((3,5))
var2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [54]:
var1-var2

array([[3., 7., 6., 8., 7.],
       [4., 1., 4., 7., 8.],
       [8., 0., 8., 6., 8.]])

In [55]:
var1*var2

array([[4., 8., 7., 9., 8.],
       [5., 2., 5., 8., 9.],
       [9., 1., 9., 7., 9.]])

In [56]:
var1 ** 2

array([[16, 64, 49, 81, 64],
       [25,  4, 25, 64, 81],
       [81,  1, 81, 49, 81]], dtype=int32)

In [57]:
np.square(var1)

array([[16, 64, 49, 81, 64],
       [25,  4, 25, 64, 81],
       [81,  1, 81, 49, 81]], dtype=int32)

In [58]:
np.mean(var1)

6.666666666666667

In [59]:
np.std(var1)

2.573367875415838

In [60]:
np.var(var1)

6.622222222222223

In [61]:
np.max(var1)

9

In [62]:
np.sort(var1)

array([[4, 7, 8, 8, 9],
       [2, 5, 5, 8, 9],
       [1, 7, 9, 9, 9]])

In [63]:
var1

array([[4, 8, 7, 9, 8],
       [5, 2, 5, 8, 9],
       [9, 1, 9, 7, 9]])

In [64]:
np.max(var1)

9

In [66]:
np.min(var1)

1

In [67]:
np.argsort(var1)

array([[0, 2, 1, 4, 3],
       [1, 0, 2, 3, 4],
       [1, 3, 0, 2, 4]], dtype=int64)

In [68]:
np.argmin(var1)

11

In [69]:
np.argmax(var1)

3

In [70]:
var1.reshape(3,5,1).shape

(3, 5, 1)

In [72]:
var1.T

array([[4, 5, 9],
       [8, 2, 1],
       [7, 5, 9],
       [9, 8, 7],
       [8, 9, 9]])

In [73]:
var1

array([[4, 8, 7, 9, 8],
       [5, 2, 5, 8, 9],
       [9, 1, 9, 7, 9]])

In [74]:
var1.T.shape

(5, 3)

In [75]:
var1.shape

(3, 5)

In [76]:
d1=np.random.randint(0,10,size=(3,3))
d1

array([[7, 0, 7],
       [7, 2, 0],
       [7, 2, 2]])

In [77]:
d2=np.random.randint(0,10,size=(3,2))
d2

array([[0, 4],
       [9, 6],
       [9, 8]])

In [78]:
d1.dot(d2)

array([[63, 84],
       [18, 40],
       [36, 56]])

In [79]:
var1 > var2

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True]])

In [80]:
var1 == var2

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True, False, False, False]])

In [81]:
var1 > 7

array([[False,  True, False,  True,  True],
       [False, False, False,  True,  True],
       [ True, False,  True, False,  True]])

In [83]:
var1 >= var2

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [84]:
np.argmax(var1,axis=1)

array([3, 4, 0], dtype=int64)

In [85]:
np.argmin(var1,axis=0)

array([0, 2, 1, 2, 0], dtype=int64)

In [90]:
t=np.random.randn(1,2,3)

In [91]:
t

array([[[-1.71954101,  0.28355807, -0.28061602],
        [ 0.37458511, -1.04882833, -2.11935737]]])

In [92]:
t1=np.arange(1,100,10)
t1

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])